const translations = {
    pl: {
        nav: { home: 'Strona Główna', aiStats: 'AI w Liczbach', about: 'O nas', services: 'Usługi', portfolio: 'Portfolio', contact: 'Kontakt' },
        hero: { badge: 'Wśród nielicznych w Polsce wykorzystujących AI', title: 'Twój Biznes Napędzany Sztuczną Inteligencją', subtitle: 'ST KRAKOS - Wykorzystujemy najnowsze technologie AI, aby stworzyć dla Ciebie stronę lub aplikację, która przyciąga klientów i zwiększa sprzedaż. Profesjonalne rozwiązania, które działają.', btn1: 'Poznaj nasze rozwiązania', btn2: 'Bezpłatna konsultacja' },
        aiStats: { title: 'AI w Liczbach', intro: 'Sprawdzone statystyki pokazują, dlaczego sztuczna inteligencja to przyszłość biznesu', stat1: 'firm planuje zwiększyć inwestycje w AI do 2025 roku', stat2: 'wzrost produktywności dzięki wykorzystaniu AI', stat3: 'wartość AI dla globalnej gospodarki do 2030', stat4: 'firm zauważa poprawę jakości decyzji dzięki AI' },
        about: { title: 'O ST KRAKOS', intro: 'Poznaj zespół ekspertów, który przekształca technologie AI w realne korzyści biznesowe', h2_1: 'Tworzymy Przyszłość z AI', p1: 'ST KRAKOS to eksperci, którzy przekształcają nowoczesne technologie sztucznej inteligencji w realne korzyści dla Twojego biznesu. Projektujemy i budujemy strony internetowe oraz aplikacje, które łączą elegancki design z inteligentnymi funkcjami, zapewniając Twojej firmie przewagę konkurencyjną.', h2_2: 'Dlaczego My?', feat1: 'Technologie AI', feat1d: 'wykorzystujemy najnowsze narzędzia wspomagane sztuczną inteligencją', feat2: 'Indywidualne podejście', feat2d: 'każdy projekt dostosowujemy do Twoich potrzeb', feat3: 'Szybka realizacja', feat3d: 'od koncepcji do wdrożenia w rekordowym czasie', feat4: 'Najwyższa jakość', feat4d: 'profesjonalne rozwiązania, które przyciągają klientów' },
        services: { title: 'Nasze Usługi', intro: 'Oferujemy kompleksowe rozwiązania webowe dostosowane do Twoich potrzeb. Od szybkich landing page\'ów po zaawansowane aplikacje - każdy projekt realizujemy z dbałością o szczegóły i najwyższą jakość.', cert: 'Po zrealizowaniu projektu otrzymujesz certyfikat potwierdzający, że Twoja firma wykorzystuje sztuczną inteligencję w swojej działalności.', cat1: '⚡ Szybkie Projekty', cat1d: 'Lekkie i estetyczne realizacje, które pozwalają szybko zaistnieć w sieci.', cat2: '🎯 Projekty Średnie', cat2d: 'Kompleksowe strony internetowe i proste systemy zarządzania treścią.', cat3: '🚀 Projekty Złożone', cat3d: 'Aplikacje webowe z zaawansowanymi funkcjami, idealne jako MVP dla biznesu.', lp: 'Landing Page', lpd: 'Jednostronicowa strona z sekcjami: hero, o nas, oferta, kontakt. Nowoczesny design, responsywność, animacje.', lpf: 'Dla: Start-upy, jednoosobowe działalności, eventy', mod: 'Modyfikacje Stron', modd: 'Ulepszenie istniejącej strony. Poprawa błędów, optymalizacja, nowe sekcje, przyspieszenie działania.', modf: 'Dla: Firmy z istniejącą stroną', elem: 'Elementy Interaktywne', elemd: 'Animacje, galerie, FAQ. Nowoczesne efekty zwiększające zaangażowanie użytkowników.', elemf: 'Dla: Wszystkie firmy', web: 'Strona Firmowa', webd: 'Wielostronicowa strona (5-15 podstron), projekt graficzny, blog, CMS, formularze, SEO.', webf: 'Dla: Firmy usługowe, agencje, biznesy', panel: 'Panele i Backend', paneld: 'System do zarządzania danymi. Logowanie, panel admin, CRUD, baza danych, API.', panelf: 'Dla: Firmy potrzebujące narzędzi wewnętrznych', int: 'Integracje', intd: 'Połączenie z CRM, automatyzacje, generowanie PDF, wysyłka maili, webhooki.', intf: 'Dla: Firmy automatyzujące pracę', app: 'Aplikacja Webowa (MVP)', appd: 'Baza danych, logowanie, panel użytkownika, dashboard. Gotowe rozwiązanie dla Twojego biznesu.', appf: 'Dla: Startupy, firmy usługowe', res: 'System Rezerwacji', resd: 'Kalendarz z zapisami, formularz rezerwacji, potwierdzenia e-mail. Proste i skuteczne.', resf: 'Dla: Fryzjerzy, trenerzy, gabinety', rt: 'Moduł Real-Time', rtd: 'Czat, statusy online, powiadomienia. Komunikacja w czasie rzeczywistym.', rtf: 'Dla: Aplikacje komunikacyjne, narzędzia zespołowe', dash: 'Dashboard Analityczny', dashd: 'Wykresy, statystyki, eksport danych. Wgląd w kluczowe metryki biznesowe.', dashf: 'Dla: Firmy potrzebujące analizy danych' },
        tech: { title: 'Nasze Narzędzia i Technologie', intro: 'Wykorzystujemy najnowsze narzędzia AI i technologie, aby tworzyć rozwiązania, które działają. Każdy projekt realizujemy z najwyższą jakością.', t1: 'Narzędzia AI', t1d: 'Najnowsze narzędzia wspomagane sztuczną inteligencją. Szybsza realizacja projektów przy zachowaniu najwyższej jakości.', t2: 'Środowisko Programistyczne', t2d: 'Zaawansowane narzędzia deweloperskie. Stabilne, bezpieczne i wydajne aplikacje z wykorzystaniem sprawdzonych rozwiązań.', t3: 'Frameworki i Biblioteki', t3d: 'Nowoczesne technologie webowe. Szybkie działanie, bezpieczeństwo i kompatybilność na wszystkich urządzeniach.', cta: 'Technologie to nasza specjalność - skup się na biznesie, resztą zajmiemy się my.' },
        portfolio: { title: 'Nasze Realizacje', intro: 'Oto przykłady naszych projektów realizowanych dla klientów. Każdy projekt to unikalne rozwiązanie dostosowane do potrzeb biznesowych.', p1: 'Nesyra.com', p1d: 'Projekt realizowany dla naszego klienta. Wersja beta strony internetowej, która prezentuje nowoczesne podejście do biznesu. Jesteśmy otwarci na współpracę z wszystkimi, którzy są otwarci na nowe propozycje biznesowe.', p2: 'Misja Czysta Woda', p2d: 'Kolejny projekt realizowany dla naszego klienta - Misja Czysta Woda. Strona internetowa dedykowana promocji inicjatyw związanych z ochroną środowiska i czystością wód. Projekt łączy nowoczesny design z przekazem ekologicznym, tworząc platformę informacyjną dla osób zaangażowanych w ochronę przyrody.', view: 'Zobacz projekt →' },
        contact: { title: 'Skontaktuj się z nami', intro: 'Masz pytania? Chcesz dowiedzieć się więcej o naszych usługach? Skontaktuj się z nami bezpośrednio!', info: 'Informacje kontaktowe', email: 'Email:', phone: 'Telefon:' },
        footer: 'Wszystkie prawa zastrzeżone.'
    },
    en: {
        nav: { home: 'Home', aiStats: 'AI in Numbers', about: 'About', services: 'Services', portfolio: 'Portfolio', contact: 'Contact' },
        hero: { badge: 'Among the few in Poland using AI', title: 'Your Business Powered by Artificial Intelligence', subtitle: 'ST KRAKOS - We use the latest AI technologies to create a website or application for you that attracts customers and increases sales. Professional solutions that work.', btn1: 'Discover our solutions', btn2: 'Free consultation' },
        aiStats: { title: 'AI in Numbers', intro: 'Proven statistics show why artificial intelligence is the future of business', stat1: 'of companies plan to increase AI investments by 2025', stat2: 'productivity increase through AI utilization', stat3: 'AI value for the global economy by 2030', stat4: 'of companies notice improved decision quality thanks to AI' },
        about: { title: 'About ST KRAKOS', intro: 'Meet the team of experts who transform AI technologies into real business benefits', h2_1: 'Creating the Future with AI', p1: 'ST KRAKOS are experts who transform modern artificial intelligence technologies into real benefits for your business. We design and build websites and applications that combine elegant design with intelligent features, giving your company a competitive advantage.', h2_2: 'Why Us?', feat1: 'AI Technologies', feat1d: 'we use the latest AI-powered tools', feat2: 'Individual Approach', feat2d: 'we tailor each project to your needs', feat3: 'Fast Implementation', feat3d: 'from concept to deployment in record time', feat4: 'Highest Quality', feat4d: 'professional solutions that attract customers' },
        services: { title: 'Our Services', intro: 'We offer comprehensive web solutions tailored to your needs. From quick landing pages to advanced applications - we implement every project with attention to detail and the highest quality.', cert: 'After completing the project, you receive a certificate confirming that your company uses artificial intelligence in its operations.', cat1: '⚡ Quick Projects', cat1d: 'Light and aesthetic implementations that allow you to quickly establish an online presence.', cat2: '🎯 Medium Projects', cat2d: 'Comprehensive websites and simple content management systems.', cat3: '🚀 Complex Projects', cat3d: 'Web applications with advanced features, perfect as MVP for business.', lp: 'Landing Page', lpd: 'Single-page site with sections: hero, about, offer, contact. Modern design, responsiveness, animations.', lpf: 'For: Startups, solo businesses, events', mod: 'Website Modifications', modd: 'Improving an existing website. Bug fixes, optimization, new sections, speed improvements.', modf: 'For: Companies with existing websites', elem: 'Interactive Elements', elemd: 'Animations, galleries, FAQ. Modern effects that increase user engagement.', elemf: 'For: All companies', web: 'Corporate Website', webd: 'Multi-page website (5-15 pages), graphic design, blog, CMS, forms, SEO.', webf: 'For: Service companies, agencies, businesses', panel: 'Panels and Backend', paneld: 'Data management system. Login, admin panel, CRUD, database, API.', panelf: 'For: Companies needing internal tools', int: 'Integrations', intd: 'CRM connection, automation, PDF generation, email sending, webhooks.', intf: 'For: Companies automating work', app: 'Web Application (MVP)', appd: 'Database, login, user panel, dashboard. Ready solution for your business.', appf: 'For: Startups, service companies', res: 'Booking System', resd: 'Calendar with bookings, booking form, email confirmations. Simple and effective.', resf: 'For: Hairdressers, trainers, clinics', rt: 'Real-Time Module', rtd: 'Chat, online statuses, notifications. Real-time communication.', rtf: 'For: Communication apps, team tools', dash: 'Analytics Dashboard', dashd: 'Charts, statistics, data export. Insight into key business metrics.', dashf: 'For: Companies needing data analysis' },
        tech: { title: 'Our Tools and Technologies', intro: 'We use the latest AI tools and technologies to create solutions that work. We implement every project with the highest quality.', t1: 'AI Tools', t1d: 'Latest AI-powered tools. Faster project implementation while maintaining the highest quality.', t2: 'Development Environment', t2d: 'Advanced development tools. Stable, secure and efficient applications using proven solutions.', t3: 'Frameworks and Libraries', t3d: 'Modern web technologies. Fast performance, security and compatibility on all devices.', cta: 'Technology is our specialty - focus on business, we\'ll handle the rest.' },
        portfolio: { title: 'Our Projects', intro: 'Here are examples of our projects completed for clients. Each project is a unique solution tailored to business needs.', p1: 'Nesyra.com', p1d: 'Project completed for our client. Beta version of a website that presents a modern approach to business. We are open to cooperation with everyone who is open to new business proposals.', p2: 'Mission Clean Water', p2d: 'Another project completed for our client - Mission Clean Water. Website dedicated to promoting initiatives related to environmental protection and water cleanliness. The project combines modern design with an ecological message, creating an information platform for people involved in nature protection.', view: 'View project →' },
        contact: { title: 'Contact Us', intro: 'Have questions? Want to learn more about our services? Contact us directly!', info: 'Contact Information', email: 'Email:', phone: 'Phone:' },
        footer: 'All rights reserved.'
    }
}
import { renderHome } from '../pages/home.js'
import { renderHeader, renderFooter } from '../components/layout.js'
let currentLang = localStorage.getItem('lang') || 'pl'
export const setLang = (lang) => { currentLang = lang; localStorage.setItem('lang', lang); updatePage() }
export const getLang = () => currentLang
export const t = (path) => path.split('.').reduce((o, k) => o?.[k], translations[currentLang]) || path
const updatePage = () => { const content = document.getElementById('content'); if (content) renderHome(content); renderHeader(); renderFooter() }

